// <auto-generated />
namespace DailyStatus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class seed_interns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seed_interns));
        
        string IMigrationMetadata.Id
        {
            get { return "202104041245429_seed_interns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
